### ISSUE TITLE
Reconstruction result

### ISSUE THREAD

**Issue by Epiphqny** [TencentARC/Open-MAGVIT2#1]
Dear authors, thanks for your work. I tested the two models on my pictures, but the results seems not good. Is there anything wrong? thanks for you attention. Here are the two original pictures. 
![15_image_0_0_0](https://github.com/TencentARC/Open-MAGVIT2/assets/16319629/ce370e5c-0c70-4fd0-bc57-f2d22559ce3b)
![16_image_0_0_0](https://github.com/TencentARC/Open-MAGVIT2/assets/16319629/4c08aeb7-0e81-4fed-82c7-2f53b0bbdb99)
And the reconstruction using the IN128_Base: 
![0](https://github.com/TencentARC/Open-MAGVIT2/assets/16319629/edd49588-dcfb-4a5d-9565-b86bada60e53)
![8](https://github.com/TencentARC/Open-MAGVIT2/assets/16319629/e6d1172a-5898-4cf1-a9a6-d56500878d3a)
And the reconstruction using  the IN256_Base: 
![0](https://github.com/TencentARC/Open-MAGVIT2/assets/16319629/adff0a1f-2979-4350-9724-b1f340aea9cf)

![8](https://github.com/TencentARC/Open-MAGVIT2/assets/16319629/bb495438-ff9c-4720-bb21-5f6787406dc8)

Also, as describe in the README, the model achieves 0.39 rFID for 8x downsampling, but it seems the provided model is 4x downsample? There is no 8x downsample model in the links. Thanks for your help!
<img width="862" alt="image" src="https://github.com/TencentARC/Open-MAGVIT2/assets/16319629/ce0b13d3-c5f6-496d-ab59-11bd87175d38">

**Comment by RobertLuo1** [comment]
Thanks for your interest in our work. We would like to make a further clarification that when training $128 \times 128$ imagenet, our model has three downsampling layers, which means the image will be processed into $16 \times 16$. $16 \times 16$ for quantization is utilized in VQGAN and MAGVIT. Here, as stated in the caption, we use the 8x downsampling model to directly test on $256 \times 256$ images without finetuning, which means it has $32 \times 32$ 2D tokens to align with the paper that adopts 8x downsampling ratio. 
The facial reconstruction is quite hard if only trained on imagenet. But with the increase of tokens, it will get better results like directly testing on $512 \times 512$ images directly using the 8x downsampling model.

**Comment by Epiphqny** [comment]
Thanks for your quick reply, I will close the issue.
