### ISSUE TITLE
Noisy points in reconstruction results

### ISSUE THREAD

**Issue by shinshiner** [TencentARC/Open-MAGVIT2#12]
Hi, thanks for your great reproduction, I've trained it in ImageNet. An issue is there are many noisy points in reconstruction images, especially for black background, as shown in the picture. Do you have any idea about this? I've trained the model for 2 epochs, and the loss seems to not decrease, does it mean the model has converged?

Thanks!

![bad1](https://github.com/TencentARC/Open-MAGVIT2/assets/24225683/bce5d1bd-73af-4103-bbf6-758f778f2b3d)
![bad2](https://github.com/TencentARC/Open-MAGVIT2/assets/24225683/8b1ec356-18ac-4397-82df-bf86c3c6fb11)

**Comment by yyyouy** [comment]
Maybe the epoch should be 150 (in this GitHub repo), and the paper shows the result which is trained with 270 epochs.

**Comment by shinshiner** [comment]
> Maybe the epoch should be 150 (in this GitHub repo), and the paper shows the result which is trained with 270 epochs.

I'm not sure whether it is a common case in the early of training, or it has coverged to a bad local minimal. Since I observed the loss does not decrease after 2 epochs, and worry that there is no use even I train 1000 epochs. @RobertLuo1 could u provide some suggestions, is it common?

**Comment by RobertLuo1** [comment]
Hi, Thanks for your interest in our work. I assume that perhaps you did not clamp the output into (-1, 1) and then map back to RGB space.  At the early training stage, since the model is still learning, some values of pixels will be out of the range of (-1,1). I hope that will be helpful because we haven't encountered that problem during our training.

**Comment by huge123** [comment]
> > Maybe the epoch should be 150 (in this GitHub repo), and the paper shows the result which is trained with 270 epochs.
> 
> I'm not sure whether it is a common case in the early of training, or it has coverged to a bad local minimal. Since I observed the loss does not decrease after 2 epochs, and worry that there is no use even I train 1000 epochs. @RobertLuo1 could u provide some suggestions, is it common?

so is it a common case at the early training stage?
