### ISSUE TITLE
Could you Vs VQGAN-LC benchmark?

### ISSUE THREAD

**Issue by xesdiny** [TencentARC/Open-MAGVIT2#14]
see [VQGAN-LC](https://github.com/zh460045050/VQGAN-LC) is also big vocab_size quantification. Is it possible to construct an evaluation comparison?

**Comment by ShiFengyuan1999** [comment]
We release the evaluation script and report the standard evaluation metrics (e.g. Reconstruction FID) in Table 1 of README.md. **They receive the optimal results of 2.62 rFID at 16 downsample ratio and 1.29 rFID at 8 downsample ratio , while we obtain 1.53 rFID and 0.39 rFID respectively.**
