### ISSUE TITLE
Auto-Regressive Generative Model with MagVitV2 Tokenizer

### ISSUE THREAD

**Issue by youngsheen** [TencentARC/Open-MAGVIT2#19]
Hello, the performance of the tokenizer is impressive. I'm particularly interested in the development of the auto-regressive generative model that is being trained with the MagVitV2 tokenizer. I believe this combination has great potential.

Could you please provide any updates on the progress of this model? I'm eagerly looking forward to its release and the opportunities it may offer to the community.

**Comment by ShiFengyuan1999** [comment]
Hi @youngsheen, thanks for your interest in our work. We are working on autoregressive generation with our Open-MAGVIT-2 tokenizer, and the training process is still ongoing, but it will be done soon. Stay tuned!
