### ISSUE TITLE
Better to put `self.model_ema = LitEma(self)` before `self.init_from_ckpt(...)`?

### ISSUE THREAD

**Issue by AIWanderer-X** [TencentARC/Open-MAGVIT2#27]
https://github.com/TencentARC/Open-MAGVIT2/blob/6bfab153fb2fe612edbf8afa9b3a607d8337c194/taming/models/lfqgan.py#L62

Would it be better to move `self.model_ema = LitEma(self)` before the line of `self.init_from_ckpt(ckpt_path, ignore_keys=ignore_keys, stage=stage)` so that `model_ema` can load from checkpoint each time resuming training?

**Comment by RobertLuo1** [comment]
Thanks for your reminder! In our v2, we have already changed the order.
