### ISSUE TITLE
Questions about the update timeline

### ISSUE THREAD

**Issue by Liam-lyr** [TencentARC/Open-MAGVIT2#28]
Hi, thank you very much for the amazing work! I noticed in #26 that you mentioned a “next huge update.” Could you please let us know if there is a specific or rough timeline for this update, including the planned updates for the video tokenizer in the future?

**Comment by RobertLuo1** [comment]
Hi! Thanks for your interest to our work. Currently, we have finished training a small AR Transformer using Magvit Tokenizer and we are actively working on the scaling of the AR transformer. At the same time, we also scale up training the Tokenizer. We plan to release a series of AR transformer with the tokenizer after finishing all model training. Please Stay Tune!
