### ISSUE TITLE
Do you compare your ckpt with stability's?

### ISSUE THREAD

**Issue by StarCycle** [TencentARC/Open-MAGVIT2#3]
Hi,

Do you compare your ckpt with the vae/vqvae [here](https://github.com/CompVis/latent-diffusion)?

![图片](https://github.com/TencentARC/Open-MAGVIT2/assets/33491471/596a630a-e4b6-40e6-978f-de8a17c4a241)

If the direct comparison is not reasonable because their ckpts are trained with more data, did they have a version that was only trained with imagenet data but with the same config? Or can you evaluate their ckpt on imagenet even if these are trained on more data...I just want to know which ckpt is most suitable for my current application.

Best,
StarCycle

**Comment by yxgeee** [comment]
We have added their results to our comparison table (https://github.com/TencentARC/Open-MAGVIT2?tab=readme-ov-file#-quantitative-comparison). Thank you again for the valuable suggestion!

**Comment by StarCycle** [comment]
Hi @ShiFengyuan1999 @yxgeee,

Thank you for the answer and your ckpts are so powerful!

When you apply Open-MAGVIT on your autoregressive transformer, you dont have to generate tokens one by one. You can generate image tokens in a single forward pass and generate language tokens one by one. For example, take a similar approach to the original Magvit2 or Bytedance's VAR.

Looking forward to your future progress! It's really a great work!

Best,
StarCycle

**Comment by yxgeee** [comment]
Hi @StarCycle , Thank you for the suggestion. You are welcome to contribute to our repo if you have impressive results using Open-MAGVIT2 tokenizers.
