### ISSUE TITLE
UNet Model

### ISSUE THREAD

**Issue by JeremyCJM** [TencentARC/Open-MAGVIT2#30]
I noticed that you are using the UNet of Stable Diffusion. It seems that you remove the attention in the original model. Could I know the reason behind this? In addition, did you compare the model size of yours and the MAGViT-v2?

**Comment by RobertLuo1** [comment]
Hi, Thanks for your interest. We believe it can be attributed to two factors. 1. We follow the design of MAGVIT-v2. 2. The replacement of the attention allows us to enlarge the same size of the tokenizer with MAGVIT-v2.
