### ISSUE TITLE
About the results without cfg

### ISSUE THREAD

**Issue by youngsheen** [TencentARC/Open-MAGVIT2#32]
Hi, the FID score in the paper is impressive. But I am curious about the generation results without cfg, could you provide the score of them? Thanks a lot.

**Comment by RobertLuo1** [comment]
Hi! Thanks for your interest on our work. We haven't conducted any experiments without cfg. I think simply set the cfg_scale=1 is not appropriate since our training adopts the 0.1 dropout for class embedding. I think you should consider retrain the model without the dropout.
