### ISSUE TITLE
Could we make it a package?

### ISSUE THREAD

**Issue by vinyesm** [TencentARC/Open-MAGVIT2#33]
First thanks for this awesome work and making it open source! I have been using the tokenizer (inference) for my experiments. It would be really great if this repo was a package so we could load the model easily after a pip install without having to checkout the code.

**Comment by RobertLuo1** [comment]
Thanks for your PR and interest on our work. I will take some time to process it in order to avoid potential conflicts.

**Comment by vinyesm** [comment]
I made some other changes (only structure, no code changes) and uploaded a version of the package to pypi so it is easy to test.

github: https://github.com/vinyesm/Open-MAGVIT2
pypi: https://pypi.org/project/open-magvit2/

**Comment by RobertLuo1** [comment]
Hi, Recently I have been busy with some stuff. Sorry for reply late. I have checked the pull request. Since we will make some updates in the future, I think you can make it an extended branch as for the package.  We will update our ReadME later. Again, thanks for your PR.
