### ISSUE TITLE
Could you improve the mushroom shape in the sample?

### ISSUE THREAD

**Issue by TTPlanetPig** [TencentARC/Open-MAGVIT2#36]
The mushroom, which is not as cool as the one we get from HunyuanDiT, also from Tencent, I know both team like the mushroom, but please make it better looking!
Really appreciate!
![IMG_9735](https://github.com/user-attachments/assets/3b98cf93-e387-46e4-86f4-51aabe4e0fb1)

**Comment by RobertLuo1** [comment]
Hi! Thanks for your attention! I think they have incorporated more aesthetic data to train the model. We only train it on ImageNet. Currently, we are working on assigning our model with text2img ability. Stay tuned for the next update.
