### ISSUE TITLE
There is a problem with the inference result

### ISSUE THREAD

**Issue by wen020** [TencentARC/Open-MAGVIT2#38]
I used the following script to inference, but the resulting image was white. Does anyone know what the problem is?
code
[code.zip](https://github.com/user-attachments/files/17338155/code.zip)
input
![2 (1)](https://github.com/user-attachments/assets/37cfde7b-9e49-48b9-b8be-55be374ce3ca)

output
![reconstructed_image2](https://github.com/user-attachments/assets/be93a0af-bfee-449a-b2ce-1dc0c8f17e15)

**Comment by RobertLuo1** [comment]
Hi, Thanks for your attention to our work. I have read through your code, and I find that you should normalize the image in the range of (-1, 1) before inputting it into the model. And can you provide this image? By the way, can you please give us a star if it is helpful. :)
