### ISSUE TITLE
encoder和decoder的结果不一致。

### ISSUE THREAD

**Issue by Mr-Harry** [TencentARC/Open-MAGVIT2#6]
我发现在你进行图像编码和解码之后出现了光影不一致的情况，还有色彩转移到其他部分的情况。你有什么方案或者会修复它么？

**Comment by yxgeee** [comment]
Generally, the results would get better when using more tokens to represent it. So you can try to feed an image with a larger resolution (e.g., $512 \times 512$).

**Comment by RobertLuo1** [comment]
Can you show some examples for better targeting the problem you mentioned?

**Comment by StarCycle** [comment]
@Mr-Harry 其实还好，您可以参考[这里](https://github.com/lucasjinreal/LLaVA-Magvit2)的效果和推理代码
