### ISSUE TITLE
How long does it take to train this model?

### ISSUE THREAD

**Issue by StarCycle** [TencentARC/Open-MAGVIT2#7]
How long does it take to train this model with 32 V100?

**Comment by yxgeee** [comment]
About 4 days.

**Comment by StarCycle** [comment]
So quick! I am waiting for you ckpt with more training data & video!

**Comment by wsxwd** [comment]
> About 4 days.

4 days for train 128*128 resolution(imagenet_lfqgan_128_L.yaml) or 256* 256(imagenet_lfqgan_256_L.yaml)?
